# Generated by Django 2.2.2 on 2019-07-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news_db',
        ),
    ]
